fixup! apps/examples/mpu: Fix mpu test addresses
In commit b25c5ed, recovery test of loadable sample gets
kernel addresses through testcase driver. But that command
is under CONFIG_EXAMPES_MPU_TEST.
It causes build break with loadable enabled and mpu test disabled.

CC: recovery.c
recovery.c: In function 'assert_thread':
recovery.c:54:14: error: 'MPUTEST_KERNEL_CODE' undeclared (first use in this function)
   obj.type = MPUTEST_KERNEL_CODE;
              ^~~~~~~~~~~~~~~~~~~
recovery.c:54:14: note: each undeclared identifier is reported only once for each function it appears in
recovery.c:55:9: warning: implicit declaration of function 'ioctl' [-Wimplicit-function-declaration]
   ret = ioctl(tc_fd, TESTIOC_MPUTEST, &obj);
         ^~~~~
recovery.c:55:22: error: 'TESTIOC_MPUTEST' undeclared (first use in this function)
   ret = ioctl(tc_fd, TESTIOC_MPUTEST, &obj);
                      ^~~~~~~~~~~~~~~
recovery.c:67:14: error: 'MPUTEST_APP_ADDR' undeclared (first use in this function)
   obj.type = MPUTEST_APP_ADDR;
              ^~~~~~~~~~~~~~~~
recovery.c:36:21: warning: unused variable 'addr' [-Wunused-variable]
  volatile uint32_t *addr;
                     ^~~~
/root/tizenrt/os/../loadable_apps/loadable.mk:65: recipe for target 'recovery.o' failed

This commit adds the dependency with loadable recovery test and
example mpu test to resolve above.

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>