board/esp32_devkit: fix build errors and warnings
1. use #if defined instead of #if because it checks definition, not value

CC:  spiram_psram.c
spiram_psram.c: In function 'psram_enable':
spiram_psram.c:625:5: warning: "CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V" is not defined [-Wundef]
 #if CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V
     ^
CC:  spiram.c
spiram.c:63:5: warning: "CONFIG_SPIRAM_SPEED_40M" is not defined [-Wundef]
 #if CONFIG_SPIRAM_SPEED_40M && CONFIG_ESPTOOLPY_FLASHFREQ_40M
     ^
spiram.c:65:7: warning: "CONFIG_SPIRAM_SPEED_40M" is not defined [-Wundef]
 #elif CONFIG_SPIRAM_SPEED_40M && CONFIG_ESPTOOLPY_FLASHFREQ_80M
       ^

2. use kregionx_size instead of regionx_size because it was renamed previous commit

spiram.c: In function 'esp_spiram_test':
spiram.c:75:28: error: 'regionx_size' undeclared (first use in this function)
 #define CONFIG_SPIRAM_SIZE regionx_size[1]
                            ^
spiram.c:90:13: note: in expansion of macro 'CONFIG_SPIRAM_SIZE'
  size_t s = CONFIG_SPIRAM_SIZE;
             ^
spiram.c:75:28: note: each undeclared identifier is reported only once for each function it appears in
 #define CONFIG_SPIRAM_SIZE regionx_size[1]
                            ^
spiram.c:90:13: note: in expansion of macro 'CONFIG_SPIRAM_SIZE'
  size_t s = CONFIG_SPIRAM_SIZE;
             ^
spiram.c: In function 'esp_spiram_get_size':
spiram.c:75:28: error: 'regionx_size' undeclared (first use in this function)
 #define CONFIG_SPIRAM_SIZE regionx_size[1]
                            ^
spiram.c:157:9: note: in expansion of macro 'CONFIG_SPIRAM_SIZE'
  return CONFIG_SPIRAM_SIZE;
         ^
spiram.c:158:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [spiram.o] Error 1

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>