testcase/network: fix compilation errors
Change a type casting to (unsigned long), because of ioctl's implemetation.
  le_tc/network/tc_net_ether.c: In function 'tc_net_ether_ntoa_p':
  le_tc/network/tc_net_ether.c:64:31: error: passing argument 3 of 'ioctl' makes integer from pointer without a cast [-Werror]
    ret = ioctl(fd, SIOCGIFCONF, &ifcfg);
                                ^
  In file included from le_tc/network/tc_net_ether.c:32:0:
  /home/sunghan/Work/TinyAra/TizenRT_forked/os/include/sys/ioctl.h:140:5: note: expected 'long unsigned int' but argument is of type 'struct ifconf *'
   int ioctl(int fd, int req, unsigned long arg);
       ^
  le_tc/network/tc_net_ether.c:68:33: error: passing argument 3 of 'ioctl' makes integer from pointer without a cast [-Werror]
    ret = ioctl(fd, SIOCGIFHWADDR, &tmp);
                                 ^
  In file included from le_tc/network/tc_net_ether.c:32:0:
  /home/sunghan/Work/TinyAra/TizenRT_forked/os/include/sys/ioctl.h:140:5: note: expected 'long unsigned int' but argument is of type 'struct ifreq *'
   int ioctl(int fd, int req, unsigned long arg);
       ^

Add missing prototypes on tc_internal.h
  le_tc/network/network_tc_main.c: In function 'tc_network_main':
  le_tc/network/network_tc_main.c:100:2: error: implicit declaration of function 'net_dhcpc_main' [-Werror=implicit-function-declaration]
    net_dhcpc_main();
    ^
  le_tc/network/network_tc_main.c:106:2: error: implicit declaration of function 'net_inet_main' [-Werror=implicit-function-declaration]
    net_inet_main();
    ^
  le_tc/network/network_tc_main.c:109:2: error: implicit declaration of function 'net_ether_main' [-Werror=implicit-function-declaration]
    net_ether_main();
    ^
  le_tc/network/network_tc_main.c:112:2: error: implicit declaration of function 'net_netdb_main' [-Werror=implicit-function-declaration]
    net_netdb_main();
    ^
  le_tc/network/network_tc_main.c:115:2: error: implicit declaration of function 'net_dup_main' [-Werror=implicit-function-declaration]
    net_dup_main();
    ^

Includes <netinet/ether.h>
  le_tc/network/tc_net_ether.c: In function 'tc_net_ether_ntoa_p':
  le_tc/network/tc_net_ether.c:72:2: error: implicit declaration of function 'ether_ntoa' [-Werror=implicit-function-declaration]
    buffer = (FAR char *)ether_ntoa((struct ether_addr *)sa->sa_data);
    ^