le_tc/kernel: Fix build error in tc_tash_heapinfo
The variable 'pid' is used only in code snippet which is under 'CONFIG_HEAPINFO_GROUP'.

So when 'CONFIG_HEAPINFO_GROUP' is disabled following build error occurs,

le_tc/kernel/tc_tash_heapinfo.c:184:12: error: unused variable 'pid' [-Werror=unused-variable]
  pthread_t pid;
              ^
			  cc1: all warnings being treated as errors

This patch fixes above build error by wrapping variable 'pid' with 'CONFIG_HEAPINFO_GROUP'.

Signed-off-by: Lokesh B V <lokesh.bv@partner.samsung.com>