configs/*/Make.defs: add CXXFLAGS += -DCONFIG_WCHAR_BUILTIN
The LLVM includes wchar_t internally so that it causes a warning
as shown below:
os/include/sys/types.h:241:18: warning: redeclaration of C++ built-in type 'wchar_t' [-fpermissive]
 typedef uint16_t wchar_t;
                  ^~~~~~~

The sys/types.h include definition of wchar_t but it can be
disabled with CONFIG_WCHAR_BUILTIN. And it says
/* Wide, 16-bit character types.  wchar_t is a built-in type in C++ and
 * its declaration here may cause compilation errors on some compilers
 * if -DCONFIG_WCHAR_BUILTIN is not included in the CXXFLAGS.
 *
 * REVISIT: wchar_t belongs in stddef.h
 */
Let's add -DCONFIG_WCHAR_BUILTIN with CONFIG_LIBCXX conditional.

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>