os/syscall: Fixes build error when sched info logs enabled from menuconfig for rtl8730e
Building loadable apps or loadable ext with sched info logs enabled for RTL8730e results in error for undefined symbol g_funcnames:

arm-none-eabi-ld: /root/tizenrt/os/../build/output/libraries/libkarch.a(arm_syscall.o): in function `dump_syscall':
/root/tizenrt/os/arch/arm/src/armv7-a/arm_syscall.c:93: undefined reference to `g_funcnames'

This commit fixes the error by removing enclosing #if defined __KERNEL__ directive and unused headers so that g_funcnames definitions is not excluded by the pre-processor.