os/userspace: fix conflicting types issue for '_sdata'
/root/tizenrt/os/userspace/up_userspace.c:49:15: error: conflicting types for '_sdata'
   49 | extern void * _sdata;
      |               ^~~~~~
In file included from /root/tizenrt/os/include/tinyara/sched.h:75,
                 from /root/tizenrt/os/include/sched.h:72,
                 from /root/tizenrt/os/include/tinyara/arch.h:120,
                 from /root/tizenrt/os/userspace/up_userspace.c:43:
/root/tizenrt/os/include/tinyara/mm/mm.h:457:17: note: previous declaration of '_sdata' was here
  457 | extern uint32_t _sdata;
      |                 ^~~~~~

_sdata was defined as uint32_t in mm.h and void * in up_userspace.c.
So, match both of them to uint32_t to resolve the build break

Signed-off-by: Abhishek Akkabathula <a.akkabathul@samsung.com>