include/stdio: check a conditional for standard I/O
The standard I/Os, stdin, stdout and stderr, use the sched_getstreams
function but it is in "#if CONFIG_NFILE_DESCRIPTORS > 0 && CONFIG_NFILE_STREAMS > 0"
conditional. Some combination of config does not enable them so that
it causes compilation errors as shown below:

CC:  vi.c
In file included from vi.c:66:0:
vi.c: In function 'vi_write':
vi.c:513:13: error: invalid type argument of '->' (have 'int')
     fprintf(stderr, "ERROR: write to stdout failed: %d\n", errcode);
             ^
...
vi.c:3432:11: error: invalid type argument of '->' (have 'int')
   fprintf(stderr, "ERROR: Too many arguments\n");
           ^
make[2]: *** [vi.o] Error 1

Because there is no way to use standard I/Os without those configs,
this commit makes I/Os NULL under undefined those configs.