apps/examples/testcase/tc_umm_heap.c : Fix build warning for unused variable
le_tc/kernel/tc_umm_heap.c:144:9: error: unused variable 'alloc_size' [-Werror=unused-variable]
  size_t alloc_size = ALLOC_SIZE_VAL * sizeof(int);
         ^~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: jeongchanKim <jc_.kim@samsung.com>