configs/esp32_DevKitC/hello_with_tash: update defconfig with latest Kconfig
Current defconfig makes build break as below:

make[2]: Entering directory '/root/tizenrt/apps/shell'
CC:  tash_command.c
tash_command.c: In function 'tash_reboot':
tash_command.c:491:2: warning: implicit declaration of function 'boardctl' [-Wimplicit-function-declaration]
  boardctl(BOARDIOC_RESET, EXIT_SUCCESS);
  ^
tash_command.c:491:11: error: 'BOARDIOC_RESET' undeclared (first use in this function)
  boardctl(BOARDIOC_RESET, EXIT_SUCCESS);
           ^
tash_command.c:491:11: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [tash_command.o] Error 1

The tash reboot command needs a board reset functionality (CONFIG_BOARDCTL_RESET),
but esp32_DevKitC does not support so that the tash reboot config should be turned off.

Once menuconfig enters and exits, it checks the dependency and resolves a build issue automatically.
This commit updates defconfig by menuconfig update.

Signed-off-by: sunghan <sh924.chang@samsung.com>