fix compilation warnings
1. Include <string.h>
CC:  src/binary_manager/binary_manager_interface.c
src/binary_manager/binary_manager_interface.c: In function 'binary_manager_set_request':
src/binary_manager/binary_manager_interface.c:55:3: warning: implicit declaration of function 'strncpy' [-Wimplicit-function-declaration]
   strncpy(request_msg->data.update_bin.bin_name, data->bin_name, BIN_NAME_MAX);
   ^~~~~~~
binary_manager/binary_manager_recovery.c: In function 'binary_manager_recovery':
binary_manager/binary_manager_recovery.c:342:2: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
  memset(loading_data, 0, sizeof(char *) * (LOADTHD_ARGC + 1));
  ^~~~~~

2. Include <tinyara/binfmt/symtab.h>
CC:  task/task_execv.c
task/task_execv.c: In function 'execv':
task/task_execv.c:144:2: warning: implicit declaration of function 'exec_getsymtab' [-Wimplicit-function-declaration]
  exec_getsymtab(&symtab, &nsymbols);
  ^~~~~~~~~~~~~~
<tinyara/binfmt/binfmt.h>
task/task_execv.c:148:8: warning: implicit declaration of function 'exec' [-Wimplicit-function-declaration]
  ret = exec(path, (FAR char *const *)argv, symtab, nsymbols);
        ^~~~

3. Include "group/group.h"
CC:  task/task_terminate_unloaded.c
task/task_terminate_unloaded.c: In function 'task_terminate_unloaded':
task/task_terminate_unloaded.c:106:2: warning: implicit declaration of function 'group_leave' [-Wimplicit-function-declaration]
  group_leave(tcb);
  ^~~~~~~~~~~

4. Include <tinarya/kthread.h>
CC:  binary_manager/binary_manager.c
binary_manager/binary_manager.c: In function 'binary_manager':
binary_manager/binary_manager.c:93:8: warning: implicit declaration of function 'kernel_thread' [-Wimplicit-function-declaration]
  ret = kernel_thread(FAULTMSGSENDER_NAME, FAULTMSGSENDER_PRIORITY, FAULTMSGSENDER_STACKSIZE, binary_manager_faultmsg_sender, NULL);
        ^~~~~~~~~~~~~
binary_manager/binary_manager_load.c: In function 'binary_manager_loading':
binary_manager/binary_manager_load.c:654:8: warning: implicit declaration of function 'kernel_thread' [-Wimplicit-function-declaration]
  ret = kernel_thread(LOADINGTHD_NAME, LOADINGTHD_PRIORITY, LOADINGTHD_STACKSIZE, loading_thread, (char * const *)loading_data);
        ^~~~~~~~~~~~~

5. Add the prototypes in binary_manager.h
binary_manager/binary_manager.c:158:4: warning: implicit declaration of function 'binary_manager_update_running_state' [-Wimplicit-function-declaration]
    binary_manager_update_running_state(request_msg.requester_pid);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC:  binary_manager/binary_manager_load.c
binary_manager/binary_manager_load.c: In function 'binary_manager_update':
binary_manager/binary_manager_load.c:428:12: warning: implicit declaration of function 'binary_manager_get_index_with_name' [-Wimplicit-function-declaration]
  bin_idx = binary_manager_get_index_with_name(bin_name);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC:  binary_manager/binary_manager_binfile.c
binary_manager/binary_manager_binfile.c: In function 'binary_manager_create_entry':
binary_manager/binary_manager_binfile.c:165:12: warning: implicit declaration of function 'binary_manager_get_index_with_name' [-Wimplicit-function-declaration]
  bin_idx = binary_manager_get_index_with_name(bin_name);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

6. Include <tinyara/wdog.h>
CC:  binary_manager/binary_manager_recovery.c
binary_manager/binary_manager_recovery.c: In function 'binary_manager_recover_tcb':
binary_manager/binary_manager_recovery.c:114:9: warning: implicit declaration of function 'wd_delete' [-Wimplicit-function-declaration]
   (void)wd_delete(tcb->waitdog);
         ^~~~~~~~~

7. Include "semaphore/semaphore.h"
binary_manager/binary_manager_recovery.c:121:3: warning: implicit declaration of function 'sem_canceled' [-Wimplicit-function-declaration]
   sem_canceled(tcb, sem);
   ^~~~~~~~~~~~

8. Remove an unused line
CC:  pthread/pthread_create.c
pthread/pthread_create.c: In function 'pthread_create':
pthread/pthread_create.c:475:21: warning: unused variable 'rtcb' [-Wunused-variable]
   FAR struct tcb_s *rtcb = this_task();
                     ^~~~

9. Remove the '&' syntax because they are array variables (the name is the address).
CC:  kmm_heap/kmm_initialize.c
kmm_heap/kmm_initialize.c: In function 'kmm_get_heap':
kmm_heap/kmm_initialize.c:88:9: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
  return &g_kmmheap;
         ^~~~~~~~~~
armv7-m/up_blocktask.c: In function 'up_block_task':
armv7-m/up_blocktask.c:182:25: warning: passing argument 1 of 'up_mpu_set_register' from incompatible pointer type [-Wincompatible-pointer-types]
     up_mpu_set_register(&rtcb->stack_mpu_regs);
                         ^
In file included from /root/tizenrt/os/include/tinyara/sched.h:83:0,
                 from /root/tizenrt/os/include/sched.h:72,
                 from armv7-m/up_blocktask.c:60:
/root/tizenrt/os/include/tinyara/mpu.h:99:6: note: expected 'uint32_t * {aka unsigned int *}' but argument is of type 'uint32_t (*)[3] {aka unsigned int (*)[3]}'
 void up_mpu_set_register(uint32_t *mpu_regs);
      ^~~~~~~~~~~~~~~~~~~
armv7-m/up_releasepending.c: In function 'up_release_pending':
armv7-m/up_releasepending.c:146:25: warning: passing argument 1 of 'up_mpu_set_register' from incompatible pointer type [-Wincompatible-pointer-types]
     up_mpu_set_register(&rtcb->stack_mpu_regs);
                         ^
armv7-m/up_reprioritizertr.c: In function 'up_reprioritize_rtr':
armv7-m/up_reprioritizertr.c:197:26: warning: passing argument 1 of 'up_mpu_set_register' from incompatible pointer type [-Wincompatible-pointer-types]
      up_mpu_set_register(&rtcb->stack_mpu_regs);
                          ^
armv7-m/up_unblocktask.c: In function 'up_unblock_task':
armv7-m/up_unblocktask.c:168:25: warning: passing argument 1 of 'up_mpu_set_register' from incompatible pointer type [-Wincompatible-pointer-types]
     up_mpu_set_register(&rtcb->stack_mpu_regs);
                         ^
armv7-m/up_svcall.c:274:24: warning: passing argument 1 of 'up_mpu_set_register' from incompatible pointer type [-Wincompatible-pointer-types]
    up_mpu_set_register(&tcb->stack_mpu_regs);
                        ^
armv7-m/up_svcall.c:326:24: warning: passing argument 1 of 'up_mpu_set_register' from incompatible pointer type [-Wincompatible-pointer-types]
    up_mpu_set_register(&tcb->stack_mpu_regs);
                        ^
armv7-m/up_unblocktask_withoutsavereg.c:168:24: warning: passing argument 1 of 'up_mpu_set_register' from incompatible pointer type [-Wincompatible-pointer-types]
    up_mpu_set_register(&rtcb->stack_mpu_regs);
                        ^

10. Cover it with the conditionals
libelf/libelf_bind.c: In function 'elf_bind':
libelf/libelf_bind.c:477:1: warning: label 'ret_err' defined but not used [-Wunused-label]
 ret_err:
 ^~~~~~~
i2c/i2c_uio.c: In function 'i2c_uioctrl':
i2c/i2c_uio.c:230:36: warning: unused variable 'rdwr' [-Wunused-variable]
  FAR struct i2c_rdwr_ioctl_data_s *rdwr;
                                    ^~~~

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>