build/configs: Choose default port on availability
We can choose between ttyUSB1 and ttyACM0 port on availability
If we need to give port manually, use sudo ./dbuild.sh download port=/dev/ttyUSB1 ALL instead of sudo ./dbuild.sh download port=ttyUSB1 ALL

Output:

When both USB and UART(for Power) is connected:
 Port /dev/ttyACM0 is selected

 ############################################
 WARNINGS:
 1. Make sure the board is in DOWNLOAD MODE.
 2. Make sure NO other application like putty,
 is occupying /dev/ttyACM0.
 ############################################

================================ < Flash Partition Information > ================================
NAME       :           bl1      reserved           ftl            ss        kernel        common          app1        kernel        common          app1        userfs         micom     bootparam
SIZE(in KB):            60            40            12           400          1844          3040          1384          1844          3040          1384          2048          1280             8
Addr       :     0x8000000     0x800F000     0x8019000     0x801C000     0x8080000     0x824D000     0x8545000     0x869F000     0x886C000     0x8B64000     0x8CBE000     0x8EBE000     0x8FFE000
=================================================================================================

Starting Download...
rtl8730e_smartfs.bin not present

===================================
Start USB download in Flash
Fri Jul 12 05:32:09 UTC 2024
===================================
Number of images: 5
Found ACM device         ......    OK
Open serial port         ......    OK

USB download...
Close serial port        ......    OK
Open serial port         ......    OK
Close serial port        ......    OK
Open serial port         ......    OK
USB Prepare              ......    OK
Min address to download 0x8000000
Flash protection         ......    OK
km4_boot_all.bin download to 0x8000000
USB erase                ......    OK
USB download             ......    OK
USB checksum             ......    OK
Image download           ......    OK
kernel_rtl8730e_200204.trpk download to 0x8080000
USB erase                ......    OK
USB download             ......    OK
USB checksum             ......    OK
Image download           ......    OK
common_rtl8730e_200204.trpk download to 0x824d000
USB erase                ......    OK
USB download             ......    OK
USB checksum             ......    OK
Image download           ......    OK
app1_rtl8730e_190412.trpk download to 0x8545000
USB erase                ......    OK
USB download             ......    OK
USB checksum             ......    OK
Image download           ......    OK
bootparam.bin download to 0x8ffe000
USB erase                ......    OK
USB download             ......    OK
USB checksum             ......    OK
Image download           ......    OK
EVB reset                ......    OK
Close serial port        ......    OK
Complete USB download
Fri Jul 12 05:32:22 UTC 2024

Download COMPLETE!

when only UART is connected,
ls: cannot access '/dev/ttyACM*': No such file or directory

 Port /dev/ttyUSB1 is selected

 ############################################
 WARNINGS:
 1. Make sure the board is in DOWNLOAD MODE.
 2. Make sure NO other application like putty,
 is occupying /dev/ttyUSB1.
 ############################################

================================ < Flash Partition Information > ================================
NAME       :           bl1      reserved           ftl            ss        kernel        common          app1        kernel        common          app1        userfs         micom     bootparam
SIZE(in KB):            60            40            12           400          1844          3040          1384          1844          3040          1384          2048          1280             8
Addr       :     0x8000000     0x800F000     0x8019000     0x801C000     0x8080000     0x824D000     0x8545000     0x869F000     0x886C000     0x8B64000     0x8CBE000     0x8EBE000     0x8FFE000
=================================================================================================

Starting Download...

==========================
Downloading bl1 binary
==========================

Number of Images: 1

Download km4_boot_all.bin to: 0x08000000

Open serial port         ......    OK

UART download...
Check download mode      ......    OK
Download flashloader     ......    OK
error: Flash is locked! Try to unlock...
Flash protection         ......    OK
Erase flash              ......    OK
Download image           ......    OK
Check checksum           ......    OK
Close serial port        ......    OK

==========================
Downloading kernel binary
==========================

Number of Images: 1

Download kernel_rtl8730e_200204.trpk to: 0x08080000

Open serial port         ......    OK

UART download...
Check download mode      ......    OK
Download flashloader     ......    OK
Flash protection         ......    OK
Erase flash              ......    OK
Download image           ......    OK
Check checksum           ......    OK
Close serial port        ......    OK

==========================
Downloading common binary
==========================

Number of Images: 1

Download common_rtl8730e_200204.trpk to: 0x0824D000

Open serial port         ......    OK

UART download...
Check download mode      ......    OK
Download flashloader     ......    OK
Flash protection         ......    OK
Erase flash              ......    OK
Download image           ......    OK
Check checksum           ......    OK
Close serial port        ......    OK

==========================
Downloading app1 binary
==========================

Number of Images: 1

Download app1_rtl8730e_190412.trpk to: 0x08545000

Open serial port         ......    OK

UART download...
Check download mode      ......    OK
Download flashloader     ......    OK
Flash protection         ......    OK
Erase flash              ......    OK
Download image           ......    OK
Check checksum           ......    OK
Close serial port        ......    OK

==========================
Downloading userfs binary
==========================
rtl8730e_smartfs.bin not present

==========================
Downloading bootparam binary
==========================

Number of Images: 1

Download bootparam.bin to: 0x08FFE000

Open serial port         ......    OK

UART download...
Check download mode      ......    OK
Download flashloader     ......    OK
Flash protection         ......    OK
Erase flash              ......    OK
Download image           ......    OK
Check checksum           ......    OK
Close serial port        ......    OK

Download COMPLETE!

Signed-off-by: Tirtha-Samsung <biswas.t@samsung.com>