kernel/binfmt/libelf_sections.c : Fix to get binary name
The binary name is in binary_s, not in bin_addr_info_t.
(It was removed from bin_addr_info_t in previous commit.)

libelf/libelf_sections.c: In function 'elf_save_bin_section_addr':
libelf/libelf_sections.c:229:42: error: 'bin_addr_info_t {aka struct bin_addr_info_s}' has no member named 'bin_name'; did you mean 'bin_idx'?
   lldbg("[%s] text_addr : %x\n", bin_info->bin_name, bin_info->text_addr);

Signed-off-by: jeongchanKim <jc_.kim@samsung.com>