iotivity : remove unsupported strings.h for tizenrt
Without this patch, compilation would fail on latest arm gcc with below error.
It can be reproduced by building artik053/st_things configuration
using 6.3.1 arm gcc toolchain.

Compilation Error:
-----------------
/root/tizenrt/os/include/string.h:83:29: error: expected identifier or '(' before 'void'
 #define bcopy(b1, b2, len) (void)memmove(b2, b1, len)
                             ^
/root/tizenrt/os/include/string.h:80:22: error: expected identifier or '(' before 'void'
 #define bzero(s, n) (void)memset(s, 0, n)
-----------------

Root Cause:
-------------
1. Wrong substitutions happened during pre-processing, because strings.h was included
   from toolchain which is not compatible with tizenrt.

	Pre-Processed Output
	-------------------
	int bcmp (const void *, const void *, size_t);
	void
	# 30 "/home/<user>/toolchain/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/strings.h"
	     (void)memmove(
	# 30 "/home/<user>/toolchain/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/strings.h" 3
	     void *
	# 30 "/home/<user>/toolchain/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/strings.h"
	     ,
	# 30 "/home/<user>/toolchain/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/strings.h" 3
	     const void *
	# 30 "/home/<user>/toolchain/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/strings.h"
	     ,
	# 30 "/home/<user>/toolchain/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/strings.h" 3
	     size_t
	# 30 "/home/<user>/toolchain/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/strings.h"
	     )
	# 30 "/home/<user>/toolchain/gcc-arm-none-eabi-6-2017-q1-update/arm-none-eabi/include/strings.h" 3
                                                 ;
	void
	--------------------

2.strings.h is included from toolchain because, it is included in few iotivity
  source files as below and TizenRT doesn't provide strings.h, hence it got
  included from toolchain.
	#ifdef HAVE_STRINGS_H
	#include <strings.h>
	#endif

3. HAVE_STRINGS_H configuration is present in iotivity to check whether
   system provides this header or not.
   Hence for tizenrt case HAVE_STRINGS_H should not have defined.
   HAVE_STRINGS_H is an auto generated config by parsing list of headers available
   in the system defined in the iotvity build scripts.

4. Problem was, strings.h present in the defined list of headers available
   for TizenRT even though tizenrt doesnt provide this header. TizenRT has only
   string.h.

Solution:
---------
This patch removes strings.h from the list of headers available for tizenrt in
iotivity build scripts.

Signed-off-by: Manohara HK <manohara.hk@samsung.com>