lm3s6965-ek: Fix build error in up_leds
The variable 'g_nest' is used in code snippet which is under 'CONFIG_ARCH_LEDS'.

when 'CONFIG_ARCH_LEDS' is disabled in lm3s6965-ek board configurations following build error occurs,

up_leds.c:107:16: error: 'g_nest' defined but not used [-Werror=unused-variable]
 static uint8_t g_nest;
                 ^
				 cc1: all warnings being treated as errors

This patch fixes the above build error by wrapping variable 'g_nest' with 'CONFIG_ARCH_LEDS'.

Signed-off-by: Lokesh B V <lokesh.bv@partner.samsung.com>