board/rtl8721csm: move the location of mpu_set_nregion_board_specific calling
The mpu_set_nregion_board_specific is built with CONFIG_ARM_MPU but
current app_start calls without that conditional. It causes build break as below.
LD: tinyara
/root/tizenrt/os/arch/arm/src/board/libboard.a(rtl8721dhp_app_start.o): In function `app_start':
/root/tizenrt/os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/ram_hp/rtl8721dhp_app_start.c:1343: undefined reference to `mpu_set_nregion_board_specific'

Let's move the location of mpu_set_nregion_board_specific calling into CONFIG_ARM_MPU conditional
and include missing headers to use that.

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>