tools/nxfuse: fix build warnings
1. add missing */ at end of comments

src/nxfuse.h:63:1: warning: "/*" within comment [-Wcomment]
 /* The logical sector number of the root directory. */
 ^

2. define prototypes of implicit declarations
src/tinyara_services.c:388:3: warning: implicit declaration of function 'filemtd_teardown' [-Wimplicit-function-declaration]
   filemtd_teardown(mtd);
   ^
src/tinyara_services.c:377:8: warning: implicit declaration of function 'filemtd_initialize' [-Wimplicit-function-declaration]
  mtd = filemtd_initialize(datasource, offset, pagesize, erasesize);
        ^

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>