arch/artik05x, sidk_s5jt200: fix compilation errors on partition and automount functionalities
1. ARTIK05X_AUTOMOUNT and SIDK_S5JT200_AUTOMOUNT use mtd functionality and mtd is in FILE_DESCRIPTORS
  conditional. So, they should have a dependancy with NFILE_DESCRIPTORS.
  This commit fixs below:
/os/arch/arm/src/board/libboard.a(artik05x_tash.o): In function `artik05x_configure_partitions':
/os/arch/arm/src/artik05x/src/artik05x_tash.c:132: undefined reference to `progmem_initialize'
/os/arch/arm/src/artik05x/src/artik05x_tash.c:171: undefined reference to `ftl_initialize'
/os/arch/arm/src/artik05x/src/artik05x_tash.c:200: undefined reference to `mtd_setpartitionname'
/os/arch/arm/src/artik05x/src/artik05x_tash.c:162: undefined reference to `mtd_partition'
/os/arch/arm/src/artik05x/src/artik05x_tash.c:178: undefined reference to `mtdconfig_register'
/os/arch/arm/src/artik05x/src/artik05x_tash.c:186: undefined reference to `smart_initialize'

2. Some automount functionality is in board_app_initialize without any conditional.
  But that uses mount function and mount is controled by configuration.
  When mount is not enabled, automount functionality should not work.
  This commit covers them with AUTOMOUNT config and fixs below:
/os/arch/arm/src/board/libboard.a(artik05x_tash.o): In function `board_app_initialize':
/os/arch/arm/src/artik05x/src/artik05x_tash.c:331: undefined reference to `mount'

3. RTC driver uses file operation so that NFILE_DESCRIPTORS should be enabled.
  This commit makes a dependancy RTC with that and fix below:
/os/arch/arm/src/artik05x/src/artik05x_tash.c:378: undefined reference to `rtc_initialize'