drivers/spi: remove redifinition of spidbg to dbg
SPI has the spidbg to print debug messages.
SPI debug message is definitely not important enough to use
dbg instead of spidbg.
Because of this, spi messages are printed at every boot time
when debug is enabled without spi debug.

up_spiinitialize: Prepare SPI0 for Master operation
spi_uioregister: -->spi_uioregister     spi/spi_uio.c:214
spi_uioregister: Registering /dev/spi-0
up_spiinitialize: Prepare SPI1 for Master operation
spi_uioregister: -->spi_uioregister     spi/spi_uio.c:214
spi_uioregister: Registering /dev/spi-1
up_spiinitialize: Prepare SPI2 for Master operation
spi_uioregister: -->spi_uioregister     spi/spi_uio.c:214
spi_uioregister: Registering /dev/spi-2
up_spiinitialize: Prepare SPI3 for Master operation
spi_uioregister: -->spi_uioregister     spi/spi_uio.c:214
spi_uioregister: Registering /dev/spi-3

Each module should use each specified dbg.
Let's remove redefinition of spidbg to dbg.

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>