configs: add CONFIG_NPTHREAD_DESTRUCTOR_ITERATIONS on all of defconfigs
To use pthread key feature, CONFIG_NPTHREAD_DESTRUCTOR_ITERATIONS
shoule be defined. This commit fixs below build breaks.

pthread/pthread_keydestroy.c: In function 'pthread_key_destroy':
pthread/pthread_keydestroy.c:85:21: error: 'CONFIG_NPTHREAD_DESTRUCTOR_ITERATIONS' undeclared (first use in this function)
   if (destr_count < PTHREAD_DESTRUCTOR_ITERATIONS) {
                     ^