testcase/kernel: cover testcases with proper conditionals
1. In stdio testcase
When CONFIG_LIBC_STRERROR is disabled, testcase makes below error
due to not used variables.

CC:  le_tc/kernel/tc_libc_stdio.c
le_tc/kernel/tc_libc_stdio.c: In function 'tc_libc_stdio_perror':
le_tc/kernel/tc_libc_stdio.c:484:14: error: unused variable 'test_msg' [-Werror=unused-variable]
  const char *test_msg;
              ^~~~~~~~
le_tc/kernel/tc_libc_stdio.c:483:8: error: unused variable 'result_msg' [-Werror=unused-variable]
  char *result_msg = "No data available";
        ^~~~~~~~~~
==> Cover them with a CONFIG_LIBC_STRERROR conditional.

2. In unistd testcase
When ENV is disabled, CONFIG_LIB_HOMEDIR is not defined due to dependancy.
It causes build breaks as shown below:

CC:  le_tc/kernel/tc_libc_unistd.c
In file included from le_tc/kernel/tc_internal.h:25:0,
                 from le_tc/kernel/tc_libc_unistd.c:31:
le_tc/kernel/tc_libc_unistd.c: In function 'tc_libc_unistd_chdir_getcwd':
le_tc/kernel/tc_libc_unistd.c:106:37: error: 'CONFIG_LIB_HOMEDIR' undeclared (first use in this function)
  TC_ASSERT_EQ("getcwd", strcmp(cwd, CONFIG_LIB_HOMEDIR), 0);
                                     ^
==> But CONFIG_LIB_HOMEDIR is not needed to test getcwd function.
   Because that is a failure case, just comparing between directory and cwd is correct.
   Remove CONFIG_LIB_HOMEDIR and compare them.

/TizenRT/os/../build/output/libraries/libapps.a(tc_libc_unistd.o): In function `libc_unistd_main':
tc_libc_unistd.c:(.text.libc_unistd_main+0x10): undefined reference to `getcwd'
tc_libc_unistd.c:(.text.libc_unistd_main+0x84): undefined reference to `chdir'
tc_libc_unistd.c:(.text.libc_unistd_main+0xdc): undefined reference to `getcwd'
tc_libc_unistd.c:(.text.libc_unistd_main+0x12c): undefined reference to `getcwd'
tc_libc_unistd.c:(.text.libc_unistd_main+0x160): undefined reference to `unsetenv'
tc_libc_unistd.c:(.text.libc_unistd_main+0x16c): undefined reference to `getcwd'
tc_libc_unistd.c:(.text.libc_unistd_main+0x37c): undefined reference to `chdir'
tc_libc_unistd.c:(.text.libc_unistd_main+0x3b8): undefined reference to `chdir'

==> All of testcase is not in proper conditional. It causes above errors.
   Cover them with DISABLE_SIGNALS, DISABLE_ENVIRON and PIPES

3. In pthread testcase
Pthread key functionality is valid when CONFIG_NPTHREAD_KEYS has a value which is greater than 0.
When it has 0, testcase makes below error due to not checking conditional.

CC:  le_tc/kernel/tc_pthread.c
le_tc/kernel/tc_pthread.c: In function 'pthread_key_test':
le_tc/kernel/tc_pthread.c:296:13: error: array subscript is below array bounds [-Werror=array-bounds]
   ret_chk = pthread_key_create(&key_val[key_index], NULL);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> Cover them with above conditional.

4. In signal testcase
/home/sunghan/Work/TinyAra/Forked_TizenRT/os/../build/output/libraries/libapps.a(tc_libc_signal.o): In function `libc_signal_main':
tc_libc_signal.c:(.text.libc_signal_main+0x76c): undefined reference to `timer_create'
tc_libc_signal.c:(.text.libc_signal_main+0x7cc): undefined reference to `timer_settime'
tc_libc_signal.c:(.text.libc_signal_main+0x814): undefined reference to `timer_delete'
tc_libc_signal.c:(.text.libc_signal_main+0x868): undefined reference to `timer_delete'

==> Sigpause testcase uses timer functionlity which is vaild on enabled config.
   Cover sigpause tc with !DISABLE_POSIX_TIMERS