framework/preference: Fix build issues with prefernce framework
- Add missing header file for shared and private preference.
" CC:  src/preference/private_preference.c
src/preference/private_preference.c: In function 'preference_set_int':
src/preference/private_preference.c:45:19: error: 'PREFERENCE_TYPE_INT' undeclared (first use in this function)
  data.attr.type = PREFERENCE_TYPE_INT;
                   ^~~~~~~~~~~~~~~~~~~  "

- Correct input parameter type for private preference functions to match function declarations in header file
" CC:  src/preference/private_preference.c
src/preference/private_preference.c:281:5: error: conflicting types for 'preference_set_changed_cb'
 int preference_set_changed_cb(char *key, preference_changed_cb callback, void *user_data)
     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/preference/private_preference.c:30:0:
/root/tizenrt/framework/include/preference/preference.h:195:5: note: previous declaration of 'preference_set_changed_cb' was here
 int preference_set_changed_cb(const char *key, preference_changed_cb callback, void *cb_data);
     ^~~~~~~~~~~~~~~~~~~~~~~~~
src/preference/private_preference.c:312:5: error: conflicting types for 'preference_unset_changed_cb'
 int preference_unset_changed_cb(char *key)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/preference/private_preference.c:30:0:
/root/tizenrt/framework/include/preference/preference.h:204:5: note: previous declaration of 'preference_unset_changed_cb' was here
 int preference_unset_changed_cb(const char *key);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:57: recipe for target 'private_preference.o' failed "

Signed-off-by: Amogh Hassija <a.hassija@samsung.com>