framework/dm: fix compilation and linking errors on s5j_dm_connectivity
1. The ioctl has last argument with unsigned long type. But dm gives
   it as void *. This commit fixs below:

CC:  src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c
src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c: In function 'dm_conn_get_address':
src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c:203:29: error: passing argument 3 of 'ioctl' makes integer from pointer without a cast [-Werror]
  if (ioctl(fd, SIOCGIFCONF, (void *)&ifcfg) < 0) {
                             ^
In file included from src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c:33:0:
/home/sunghan/Work/TinyAra/TizenRT_forked/os/include/sys/ioctl.h:140:5: note: expected 'long unsigned int' but argument is of type 'void *'
 int ioctl(int fd, int req, unsigned long arg);
     ^
src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c: In function 'dm_conn_get_interface':
src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c:246:29: error: passing argument 3 of 'ioctl' makes integer from pointer without a cast [-Werror]
  if (ioctl(fd, SIOCGIFCONF, (void *)&ifcfg) < 0) {
                             ^
In file included from src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c:33:0:
/home/sunghan/Work/TinyAra/TizenRT_forked/os/include/sys/ioctl.h:140:5: note: expected 'long unsigned int' but argument is of type 'void *'
 int ioctl(int fd, int req, unsigned long arg);
     ^
cc1: all warnings being treated as errors
make[1]: *** [s5j_dm_connectivity.o] Error 1

2. That file uses slsi wifi APIs and there is no dependancy with s5j arch
  so that a conditional in Make.defs should be changed.
  This commit fixs below linking error on some config combination as well:

/os/../build/output/libraries/libframework.a(s5j_dm_connectivity.o): In function `dm_cb_register_init':
/framework/src/dm/arch/sidk_s5jt200/s5j_dm_connectivity.c:104: undefined reference to `WiFiRegisterLinkCallback'