driver/mtd: fix smartfs nxfuse build error caused due to irq.h
enter_critical_section and leave_critical_section were added in
smart.c which is also used in nxfuse build to generate smartfs.
These should not be included in nxfuse host build

Error :

Compiling src/smartfs/smart.c
src/smartfs/smart.c:75:25: fatal error: tinyara/irq.h: No such file or directory
compilation terminated.
Makefile:112: recipe for target 'obj/smartfs/smart.o' failed
make[2]: Leaving directory '/root/tizenrt/tools/nxfuse'
make[2]: *** [obj/smartfs/smart.o] Error 1
Makefile.unix:822: recipe for target 'smartfs' failed

Signed-off-by: Abhishek Akkabathula <a.akkabathul@samsung.com>