testcase/kernel: remove unncessary clock dependancy
To run clock tc, CONFIG_SYSTEM_TIME64 is not mandatory.
This dependancy makes wrong selection on config and causes
compilation error when that config is disabled.

le_tc/kernel/kernel_tc_main.c: In function 'tc_kernel_main':
le_tc/kernel/kernel_tc_main.c:48:2: error: #error CONFIG_SYSTEM_TIME64 is needed for testing CLOCK TC
 #error CONFIG_SYSTEM_TIME64 is needed for testing CLOCK TC
  ^~~~~
Makefile:121: recipe for target 'kernel_tc_main.o' failed