include/errno.h: include <tinyara/config.h> to use CONFIG_XX
To check CONFIG_XX conditional, <tinyara/config.h> must be included.
The errno.h uses but does not include.
Because of this missing, it has abnormal operation.

For example, iperf source codes include <errno.h>.
But only iperf_client_api.c file builds with !CONFIG_BUILD_PROTECTED
even all of other files build with enabled conditional.
You can find a linking error in protected build as shown below:

build/output/libraries//libapps.a(iperf_client_api.o): In function `iperf_run_client':
apps/system/iperf/iperf_client_api.c:406: undefined reference to `get_errno_ptr'

Let's include <tinyara/config.h> in errno.h.

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>