configs/artik055s/nettest: Enable SCSC driver instead of none
Observed issue:

    wireless/scsc/max_buf.h:24:24:
    fatal error: utils_misc.h: No such file or directory

Also other changes are generated by using "make menuconfig",
some features were enabled by default
but to make this change minimal,
they were disabled again to align current base

Change-Id: I647c0689e6764b1b18c4eca96b041a108dcab69e
Origin: https://github.com/Samsung/TizenRT/pull/1910
Signed-off-by: Philippe Coval <p.coval@samsung.com>