apps/testcase/filesystem: fix a compilation error
SMARTFS_DEV_PATH is used inside file system testcase,
but sidk_s5jt200 and artik053 has that definition.
Other conditional defines MOUNT_DEV_DIR which is obsolete.
This commit fixs below compilation error:

CC:  le_tc/filesystem/tc_fs_procfs.c
le_tc/filesystem/tc_fs_procfs.c: In function 'tc_fs_smartfs_mksmartfs':
le_tc/filesystem/tc_fs_procfs.c:226:18: error: 'SMARTFS_DEV_PATH' undeclared (first use in this function)
  ret = mksmartfs(SMARTFS_DEV_PATH, 1);
                  ^~~~~~~~~~~~~~~~