netutils/dhcpd: fix 'defined but not used'
Fixed an error that can be found when using the latest toolchain.

dhcpd.c:300:22: error: 'g_anyipaddr' defined but not used
[-Werror=unused-const-variable=]
 static const uint8_t g_anyipaddr[4] = { 0, 0, 0, 0 };
                      ^~~~~~~~~~~

Change-Id: Ic0996cdee3ec375ee3a75a63fa3b1212496b035b
Signed-off-by: Junhwan Park <junhwan.park@samsung.com>