fixup! netutils/mdns: add support for exposing services
services, member of struct mdnsd was added in CONFIG_NETUTILS_MDNS_RESPONDER_SUPPORT.
But codes calling this were added without CONFIG.
It makes compilation error like below when extra defconfig is used.
mdnsd.c:1357:30: error: 'struct mdnsd' has no member named 'services'
  struct rr_list *svc_le = svr->services;
                              ^
make[2]: *** [mdnsd.o] Error 1