fix build warnings
1. include <sys/ioctl.h> at mpu_test.c and recovery.c

make[2]: Entering directory '/root/tizenrt/apps/examples/mpu'
CC:  mpu_test.c
mpu_test.c: In function 'mpu_tc_main':
mpu_test.c:58:10: warning: implicit declaration of function 'ioctl' [-Wimplicit-function-declaration]
    ret = ioctl(tc_fd, TESTIOC_MPUTEST, &obj);
          ^~~~~

CC: recovery.c
recovery.c: In function 'assert_thread':
recovery.c:55:9: warning: implicit declaration of function 'ioctl' [-Wimplicit-function-declaration]
   ret = ioctl(tc_fd, TESTIOC_MPUTEST, &obj);
         ^~~~~

2. move the ret variable into CONFIG_SUPPORT_COMMON_BINARY conditional
   Because it's used only in common binary functionality.

CC:  binary_manager/binary_manager_load.c
binary_manager/binary_manager_load.c: In function 'reloading_thread':
binary_manager/binary_manager_load.c:439:6: warning: unused variable 'ret' [-Wunused-variable]
  int ret;
      ^~~

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>