apps/system/vi: add dependancies with NFILE_STREAMS and NFILE_DESCRIPTORS
Vi uses file operation APIs like fopen, fread, stat and so on so that
it should have dependancies with them.
This commit fixs below linking errors:
/os/../build/output/libraries/libapps.a(vi.o): In function `vi_insertfile':
/apps/system/vi/vi.c:1113: undefined reference to `stat'
/apps/system/vi/vi.c:1128: undefined reference to `fopen'
/apps/system/vi/vi.c:1144: undefined reference to `fread'
/apps/system/vi/vi.c:1155: undefined reference to `fclose'
/os/../build/output/libraries/libapps.a(vi.o): In function `vi_main':
/apps/system/vi/vi.c:3385: undefined reference to `fprintf'
...
/os/../build/output/libraries/libapps.a(vi.o): In function `vi_main':
/apps/system/vi/vi.c:3356: undefined reference to `fprintf'