apps/cle: fix a compilation error due to FILE type of argument
The cle uses FILE type of argument but that type is valid
when NFILE_STREAMS is bigger than 0.
This commit makes a dependancy with NFILE_STREAMS to CLE.

CC:  cle.c
cle.c: In function 'cle':
cle.c:861:22: error: dereferencing pointer to incomplete type
  priv.infd = instream->fs_fd;
                      ^
cle.c:862:24: error: dereferencing pointer to incomplete type
  priv.outfd = outstream->fs_fd;
                        ^
make[2]: *** [cle.o] Error 1