include/lwip/arch: check redefinition of BYTE_ORDER
Many modules have the BYTE_ORDER definition. But only lwip
does not check redefinition so that it causes a compilation warning.

os/include/net/lwip/arch/cpu.h:52:0: warning: "BYTE_ORDER" redefined

Let's define it when it is not defined.

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>