net, fs: fix compilation errors
- Check definition of CONFIG_NET_LWIP first because LWIP_ARP and LWIP_ETHERNET are defined in lwip
CC:  net/lib_etherntoa.c
In file included from net/lib_etherntoa.c:60:0:
os/include/net/ethernet.h:101:5: error: "LWIP_ARP" is not defined [-Werror=undef]
 #if LWIP_ARP || LWIP_ETHERNET
     ^~~~~~~~
os/include/net/ethernet.h:101:17: error: "LWIP_ETHERNET" is not defined [-Werror=undef]
 #if LWIP_ARP || LWIP_ETHERNET
                 ^~~~~~~~~~~~~

- Cover them with CONFIG_NET_SOCKET conditioanl because they are valid with enabled it
CC:  vfs/fs_ioctl.c
In file included from /home/sunghan/Work/TinyAra/Forked_TizenRT/os/include/net/if.h:60:0,
                 from vfs/fs_ioctl.c:64:
os/include/sys/socket.h:306:36: error: 'struct msghdr' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 ssize_t recvmsg(int sockfd, struct msghdr *msg, int flags);
                                    ^~~~~~
os/include/sys/socket.h:307:36: error: 'struct msghdr' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 ssize_t sendmsg(int sockfd, struct msghdr *msg, int flags);
                                    ^~~~~~

- Initialize the errcode variable with invalid value, 0
CC:  vfs/fs_mkdir.c
In file included from vfs/fs_mkdir.c:61:0:
vfs/fs_mkdir.c: In function 'mkdir':
os/include/errno.h:132:33: error: 'errcode' may be used uninitialized in this function [-Werror=maybe-uninitialized]
 #define set_errno(e) do { errno = (int)(e); } while (0)
                                 ^
vfs/fs_mkdir.c:116:6: note: 'errcode' was declared here
  int errcode;
      ^~~~~~~

- Include <tinyara/spi/spi.h> which includes definition of 'struct spi_dev_s'
CC:  driver/mtd/mtd_config.c
In file included from driver/mtd/mtd_config.c:80:0:
os/include/tinyara/fs/mtd.h:269:50: error: 'struct spi_dev_s' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 FAR struct mtd_dev_s *m25p_initialize(FAR struct spi_dev_s *dev);
                                                  ^~~~~~~~~
os/include/tinyara/fs/mtd.h:280:49: error: 'struct spi_dev_s' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 FAR struct mtd_dev_s *w25_initialize(FAR struct spi_dev_s *dev);
                                                 ^~~~~~~~~

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>