testcase/kernel: fix compilation errors
1. Use sched_self() instead of this_task().
  The this_task() is a kernel internal API.

le_tc/kernel/tc_sched.c: In function 'tc_sched_task_setcancelstate':
le_tc/kernel/tc_sched.c:653:22: error: implicit declaration of function 'this_task' [-Werror=implicit-function-declaration]
  struct tcb_s *tcb = this_task();
                      ^~~~~~~~~

2. Include <sys/wait.h> to use waitpid().

le_tc/kernel/itc_libc_spawn.c: In function 'itc_libc_spawn_posix_spawnattr_setgetflags_p_all_flag':
le_tc/kernel/itc_libc_spawn.c:129:17: error: implicit declaration of function 'waitpid' [-Werror=implicit-function-declaration]
   int ret_pid = waitpid(pid, &status, 0);
                 ^~~~~~~

3. Add dependancies on TC_KERNEL_WORK_QUEUE with WorkQueue configs.

TizenRT/os/../build/output/libraries/libapps.a(kernel_tc_main.o): In function `tc_kernel_main':
TizenRT/apps/examples/testcase/le_tc/kernel/kernel_tc_main.c:180: undefined reference to `wqueue_main'