arch/arm/src/tiva: Fix build break with is_kernel_text_space() API addition
This patch fixes the following build break due to the addition of
is_kernel_text_space() API to the code for all the qemu configurations.

LD: tinyara
/root/tizenrt/os/../build/output/libraries/libarch.a(up_hardfault.o): In function `up_hardfault':
/root/tizenrt/os/arch/arm/src/armv7-m/up_hardfault.c:147: undefined reference to `is_kernel_text_space'
Makefile:199: recipe for target '../build/output/bin/tinyara' failed
make[1]: *** [../build/output/bin/tinyara] Error 1
make[1]: Leaving directory '/root/tizenrt/os/arch/arm/src'
Makefile.unix:476: recipe for target 'pass2' failed
make: *** [pass2] Error 2
"qemu/build_test" ERROR!!!

Signed-off-by: Vidisha Thapa <thapa.v@samsung.com>