fs/procfs: Fix the count of procfs entries, g_procfsentrycount
g_procfsentries has a default entry, {NULL, NULL} to avoid compile error like below.
So the count of entries should be subtracted because of this entry.

You can meet the compile error if you enable procfs, CONFIG_FS_PROCFS and exclude all entries, CONFIG_FS_PROCFS_EXCLUDE_XXX without default entry.

procfs/fs_procfs.c: In function 'procfs_readdir':
procfs/fs_procfs.c:624:27: error: array subscript is above array bounds [-Werror=array-bounds]
     name = g_procfsentries[index - priv->nentries].pathpattern;
            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
procfs/fs_procfs.c:649:28: error: array subscript is above array bounds [-Werror=array-bounds]
      name = g_procfsentries[index - priv->nentries].pathpattern;
             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
procfs/fs_procfs.c:734:30: error: array subscript is above array bounds [-Werror=array-bounds]
   if (strncmp(g_procfsentries[level1->base.index].pathpattern, g_procfsentries[level1->firstindex].pathpattern, level1->subdirlen) == 0) {
               ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
procfs/fs_procfs.c:734:30: error: array subscript is above array bounds [-Werror=array-bounds]
procfs/fs_procfs.c:734:79: error: array subscript is above array bounds [-Werror=array-bounds]
   if (strncmp(g_procfsentries[level1->base.index].pathpattern, g_procfsentries[level1->firstindex].pathpattern, level1->subdirlen) == 0) {
                                                                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
procfs/fs_procfs.c:734:79: error: array subscript is above array bounds [-Werror=array-bounds]
procfs/fs_procfs.c:737:27: error: array subscript is above array bounds [-Werror=array-bounds]
    name = &g_procfsentries[level1->base.index].pathpattern[level1->subdirlen + 1];
            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
procfs/fs_procfs.c:737:27: error: array subscript is above array bounds [-Werror=array-bounds]