fix compilation errors on i2c of artik
1. The s5j_i2c_register function will be compiled when CONFIG_S5J_I2C is enabled.
  But board_i2c_initialize function calling s5j_i2c_register is executed when CONFIG_I2C is enabled.
2. Because s5j_i2c_register function calls i2c_uioregister, S5J_I2C should have a dependancy of I2C_USERIO

/os/arch/arm/src/board/libboard.a(artik053_boot.o): In function `board_i2c_initialize':
/os/arch/arm/src/artik053/src/artik053_boot.c:130: undefined reference to `s5j_i2c_register'
/os/arch/arm/src/artik053/src/artik053_boot.c:131: undefined reference to `s5j_i2c_register'