drivers/kernel_test: fix build error
- this commit fix the build error of commit 057dec00ab9911dbcbf43379e11fc923ab31d056. error is following
- kernel_test/kernel_test_drv.c:30:10: fatal error: signal/signal.h: No such file or directory
   30 | #include "signal/signal.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated

Signed-off-by: Deepak sharma <deepak.sh@samsung.com>