smart.c: Fix compilation error with GCC 7
Definition of variables depends on CONFIG_MTD_SMART_WEAR_LEVEL

Fixes following build error:

driver/mtd/smart.c:209:22: error: ‘gWearBitToLevelMap4’ defined but not
used [-Werror=unused-const-variable=]
static const uint8_t gWearBitToLevelMap4[] = {
                      ^~~~~~~~~~~~~~~~~~~
driver/mtd/smart.c:198:22: error: ‘gWearLevelToBitMap4’ defined but not
used [-Werror=unused-const-variable=]
static const uint8_t gWearLevelToBitMap4[] = {
                      ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Jaroslaw Pelczar <j.pelczar@samsung.com>