os/mm/umm_memalign.c : Fix build warning for unused variable
umm_heap/umm_memalign.c:131:9: error: unused variable 'caller_retaddr' [-Werror=unused-variable]
  size_t caller_retaddr = 0;
         ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors

Signed-off-by: jeongchanKim <jc_.kim@samsung.com>