iotivity: Drop unused obsolete macros in iotivity_simpleserver
Observed error on ARTIK055S was:

  simpleServer.c:90:2: error: #error "undefined CONFIG_NET_<type>, check your .config"
  #error "undefined CONFIG_NET_<type>, check your .config"

Testing CONFIG_ARCH_BOARD_ARTIK055S or CONFIG_ARCH_BOARD_ARTIK05X_FAMILY
or even introduce CONFIG_NET_DEVNAME could have it solved this.

But defined NET_DEVNAME is not used anywhere,
so let's drop all those macros,
that was probably introduced earlier than code was imported.

Change-Id: I292ae9c3f1fc846e76e860e3dc04637d8a0c0885
Bug: https://github.com/Samsung/TizenRT/pull/1310
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>