arch/artik053 : trivial patch to fix linking error
This commit is trivial patch to fix linking error

1. Configuration : artik053/minimal
2. Build error log
LD: tinyara
In function `board_i2c_initialize':
artik053_boot.c:131: undefined reference to `s5j_i2c_register'
artik053_boot.c:132: undefined reference to `s5j_i2c_register'
make[1]: *** [../build/output/bin/tinyara] Error 1

CONFIG_S5J_I2C configuration is needed to use s5j_i2c_register function

Change-Id: I67fc21ae8a9493f132e5451dd65f4cd347c8afde
Signed-off-by: Jin-Seong Kim <jseong82.kim@samsung.com>