testcase: fix compilation error
TC_ASSERT_EQ_CLEANUP() was written wrongly and causes compilation errors
as following:

    CC:  ta_tc/systemio/itc/itc_uart.c
    In file included from ta_tc/systemio/itc/itc_internal.h:22:0,
                     from ta_tc/systemio/itc/itc_uart.c:34:
    ta_tc/systemio/itc/itc_uart.c: In function 'itc_iotbus_uart_write_read_p':
    ta_tc/systemio/itc/itc_uart.c:163:51: error: suggest parentheses around comparison in operand of '!=' [-Werror=parentheses]
         TC_ASSERT_EQ_CLEANUP("iotbus_uart_write", ret < 0, false, "Not able to write", iotbus_uart_stop(h_uart));
                                                       ^
    ta_tc/systemio/itc/../../../tc_common.h:48:6: note: in definition of macro 'TC_ASSERT_EQ_CLEANUP'
      if (var != ref) {\
          ^
    ta_tc/systemio/itc/itc_uart.c:168:50: error: suggest parentheses around comparison in operand of '!=' [-Werror=parentheses]
         TC_ASSERT_EQ_CLEANUP("iotbus_uart_read", ret < 0, false, "Not able to read", iotbus_uart_stop(h_uart));
                                                      ^
    ta_tc/systemio/itc/../../../tc_common.h:48:6: note: in definition of macro 'TC_ASSERT_EQ_CLEANUP'
      if (var != ref) {\
          ^
    cc1: all warnings being treated as errors

This commit fixes this.

Change-Id: I5b026b59e5e04925bec1c732cbb7de549d76fb7b
Signed-off-by: Heesub Shin <heesub.shin@samsung.com>