apps/system/util: add a dependancy FS_CMDS with NFILE_DESCRIPTORS
FS_CMDS use file operation APIs so that let's make a dependancy.
This commit fixs below:
/os/../build/output/libraries/libapps.a(fscmd.o): In function `tash_rmdir':
/apps/system/utils/fscmd.c:1058: undefined reference to `rmdir'
/os/../build/output/libraries/libapps.a(fscmd.o): In function `tash_rm':
/apps/system/utils/fscmd.c:1031: undefined reference to `unlink'
/os/../build/output/libraries/libapps.a(fscmd.o): In function `tash_umount':
/apps/system/utils/fscmd.c:985: undefined reference to `umount'
/os/../build/output/libraries/libapps.a(fscmd.o): In function `tash_mksmartfs':
/apps/system/utils/fscmd.c:827: undefined reference to `mksmartfs'
...