fixup! external/mbedtls: Add key allocation logic in mbedTLS alt layer
Commit f48b410, HAL_ECDSA_SEC_P521R1 definition was not modified
in header so that it causes a build break as shown below:

lat/ecdh_alt.c:216:19: error: 'HAL_ECDSA_SEC_P521R1' undeclared (first use in this function)
  ecc_pub.curve = HAL_ECDSA_SEC_P521R1;

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>