drivers/rtk_drv.c: fix build error for imxrt1020-evk/tc
- error is:

    wireless/realtek/wifi_util_interface/rtk_drv.c: In function 'rtk_drv_initialize':
    wireless/realtek/wifi_util_interface/rtk_drv.c:419:43: error: invalid application of 'sizeof' to incomplete type 'struct netdev'
      419 |  dev = (struct netdev *)kmm_malloc(sizeof(struct netdev));
          |                                           ^~~~~~
    wireless/realtek/wifi_util_interface/rtk_drv.c:423:5: error: dereferencing pointer to incomplete type 'struct netdev'
      423 |  dev->ifname[0] = 'w';
          |     ^~
    wireless/realtek/wifi_util_interface/rtk_drv.c:427:14: error: 'NM_WIFI' undeclared (first use in this function)
      427 |  dev->type = NM_WIFI;

- to fix this, need to include netdev_mgr.h to provide the reference of netdev, so when CONFIG_NET_NETMGR is enabled then it will take the reference from netdev_mgr.h, otherwise from lwnl.h

Signed-off-by: Deepak Sharma <deepak.sh@samsung.com>