tools/nxfuse, os/include: resolve smartfs build error
files modified: os/include/assert.h, tools/nxfuse/mknxfuse.sh

issue:
dq_cat.c and sq_cat.c needs DEBUGASSERT macro which is defined in .tizenrt/os/assert.h, but these files  are including assert.h from ubuntu.
Below warning and linking error arises:

src/queue/sq_cat.c:42:3: warning: implicit declaration of function 'DEBUGASSERT' [-Wimplicit-function-declaration]
DEBUGASSERT(queue1 != NULL && queue2 != NULL);

Linking nxfuse : error
obj/queue/dq_cat.o: In function dq_cat': /root/product/.tizenrt/tools/nxfuse/src/queue/dq_cat.c:42: undefined reference to DEBUGASSERT'

solution:
nxfuse is Linux application, it should not include TizenRT source code
1.set DEBUGASSERT() to empty when NXFUSE_HOST_BUILD is enabled
2.include os/include/assert.h as symbolic link