s5j: remove CONFIG_S5J_DMA
For now, driver implementation for DMA-330 (aka PL-330) is missing in
S5J, but Kconfig entry for it remains, making users confused. Let's
remove it. This also fixes compilation errors when CONFIG_S5J_DMA=y:

    make[1]: *** No rule to make target 's5j_dma.c', needed by 's5j_dma.o'.  Stop.
    make[1]: Leaving directory '/home/heesub/Documents/artik053/tizenrt/os/arch/arm/src'
    LibTargets.mk:236: recipe for target 'arch/arm/src/libarch.a' failed
    make: *** [arch/arm/src/libarch.a] Error 2

Change-Id: I0761e9d877fa1c972627bfec0ba691d29672a93f
Signed-off-by: Heesub Shin <heesub.shin@samsung.com>