configs/artik053s/nettest: update defconfig with latest
Because many necessary configs which was made or changed
are missing, nettest of artik053s has compilation errors.
This commit fixs compilation errors.

CC:  src/wifi_manager/wifi_manager.c
src/wifi_manager/wifi_manager.c: In function '_start_dhcpd':
src/wifi_manager/wifi_manager.c:127:31: error: 'CONFIG_WIFIMGR_SOFTAP_IFNAME' undeclared (first use in this function)
 #define WIFIMGR_SOFTAP_IFNAME CONFIG_WIFIMGR_SOFTAP_IFNAME
                               ^
...
Makefile:58: recipe for target 'wifi_manager.o' failed

CC:  wireless/scsc/dev.c
In file included from wireless/scsc/dev.h:34:0,
                 from wireless/scsc/dev.c:19:
wireless/scsc/max_buf.h:24:24: fatal error: utils_misc.h: No such file or directory
 #include "utils_misc.h"
                        ^