fix build error on procfs
Some variables are only used when CONFIG_FS_PROCFS_EXCLUDE_PROCESS is disabled.
procfs/fs_procfs.c: In function 'procfs_opendir':
procfs/fs_procfs.c:439:13: error: unused variable 'flags' [-Werror=unused-variable]
  irqstate_t flags;
             ^
procfs/fs_procfs.c: In function 'procfs_readdir':
procfs/fs_procfs.c:590:8: error: unused variable 'pid' [-Werror=unused-variable]
  pid_t pid;
        ^
procfs/fs_procfs.c:589:13: error: unused variable 'flags' [-Werror=unused-variable]
  irqstate_t flags;
             ^
procfs/fs_procfs.c:586:20: error: unused variable 'tcb' [-Werror=unused-variable]
  FAR struct tcb_s *tcb;