kdbg_date.c: Fix compilation error on GCC 7
This symbol is used only in day_of_week() function

Fixes following error:

kdbg_date.c:76:30: error: ‘g_dayofweek’ defined but not used
[-Werror=unused-const-variable=]
static FAR const char *const g_dayofweek[] = {

Signed-off-by: Jaroslaw Pelczar <j.pelczar@samsung.com>