lwip/core: fix compilation errors, usages of tcpip_input
1. The tcpip_input function is defined when NO_SYS is undefined.
  But the netif_register_with_initial_ip function uses it without conditional.
2. The prototype of tcpip_input is in tcpip.h. But when ENABLE_LOOPBACK and
  LWIP_NETIF_LOOPBACK_MULTITHREADING are not enabled, that header is not included.
  Because tcpip_input is used outside of those conditional, header should be
  included with appropriatary conditional, !NO_SYS.

 This commit fixs below:

lwip/src/core/netif.c:279:62: error: 'tcpip_input' undeclared (first use in this function)
  netif_add(netif, &ipaddr, &netmask, &gw, NULL, netif_init, &tcpip_input);
                                                              ^
lwip/src/core/netif.c:279:62: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [netif.o] Error 1