build: fix incorrect definition on build order
The target 'memstat' becomes available to be built after $(BIN) is
ready. In other words, 'memstat' depends on $(BIN). However, build rule
does not reflect this fact, and thus fails when it runs with -j option
greater than 1 as following:

    LN: include/apps to ../apps/include
    make[1]: Entering directory '/home/heesub/Documents/artik053/tinyara/apps'
    Traceback (most recent call last):
      File "./tools/memstats_gnueabil.py", line 42, in <module>
        infile = open(options.infilename,'r')
    IOError: [Errno 2] No such file or directory: '../build/output/bin/tinyara.map'
    Makefile.unix:618: recipe for target 'memstat' failed
    make: *** [memstat] Error 1
    make: *** Waiting for unfinished jobs....

This commit fixes this.

Change-Id: Ic1c7251caaa378411548bf66d3bdc73ad822fce6
Signed-off-by: Heesub Shin <heesub.shin@samsung.com>