configs/imxrt1050-evk/loadable_elf_apps: set CONFIG_MM_REGIONS to 1
Because CONFIG_RAM_REGIONx_START and SIZE have only 1 region,
the number of region should be 1.
This commit fixes build break as shown below:
CC:  mm_heap/mm_heap_regioninfo.c
mm_heap/mm_heap_regioninfo.c:5:71: error: expected expression before '}' token
 void *regionx_start[CONFIG_MM_REGIONS] = {(void *)0x80200000, (void *)};
                                                                       ^
make[2]: *** [ubin/mm_heap_regioninfo.o] Error 1
Makefile:102: recipe for target 'ubin/mm_heap_regioninfo.o' failed

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>