kernel/Kconfig: make DEV_CONSOLE dependent on NFILE_DESCRIPTORS
* Originally the issue is caused by 'mkconfig.c' tool, which
  manually adds sanity checks above assigned Kconfig rules. For instance,
  even if NFILE_DESCRIPTORS set to zero by menuconfig interface,
  'mkconfig.c' tool can enable them if DEV_CONSOLE is enabled.
  This ambiguous behaviour should be resolved by creating
  strictly Kconfig dependency.

* Steps to reproduce:
  - on sidk_s5jt200/hello enable DEV_CONSOLE

* Build error log:
  In file included from init/os_start.c:88:0:
./group/group.h:176:5: error: "CONFIG_NFILE_STREAMS" is not defined [-Werror=undef]
 #if CONFIG_NFILE_STREAMS > 0

Change-Id: I7a7eb1902f4c141b7f5609f5e0750f3eb3c73c39
Signed-off-by: Oleg Lyovin <o.lyovin@partner.samsung.com>