progmem: add prototype of up_progmem_blocksize
That is used in mtd_progmem.c file but there is no
prototype so that it causes a compilation warning as shown below:

driver/mtd/mtd_progmem.c:388:22: warning: implicit declaration of function 'up_progmem_blocksize' [-Wimplicit-function-declaration]
   size_t blocksize = up_progmem_blocksize();
                      ^~~~~~~~~~~~~~~~~~~~

Because other progmem prototypes like up_progmem_pagesize
are in progmem.h, let's add this there as well.

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>